version: 0.0
os: linux
files:
  - source: /
    destination: /data/AWS-Demo-Factory
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 400
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: root
  
